.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. arcana_qt test_arcana_qt
clean: FORCE
	$(MAKE) -C .. arcana_qt_clean test_arcana_qt_clean
check: FORCE
	$(MAKE) -C .. test_arcana_qt_check
arcana-qt arcana-qt.exe: FORCE
	 $(MAKE) -C .. arcana_qt
